### ISSUE TITLE
annotate does not add comments into BEGIN statement

### ISSUE THREAD

**Issue by xmas7** [RubyOnWorld/mailerlite-ruby#2]

**Comment by xmas7** [comment]
I do not think it is feasible because the annotate belongs to ActiveRecord::Relation, while the transaction does not know which SQL statements will be executed and each transaction can run multiple SQL statements which come from different ActiveRecord::Relation

**Comment by ben07ab** [comment]
The fact that multiple, differently annotated, relations can be inside a transaction is fine - the first relation that runs a query inside the transaction should get to comment on the BEGIN statement. This will create attribution for which relation (and line of code even) started the transaction.

Explicit transactions can do the same thing, e.g.:

```
MyTable.annotate('hello = wold').transaction do
  MyTable.create(hello: 'world')
end
```
